name: petween
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.1+3
  firebase_auth:
  firebase_storage_image: ^0.2.1
  image_picker: ^0.6.0+8
  date_format: ^1.0.6
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.8.2


  flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  image_path: "launcher/logo.jpg"


flutter:
  uses-material-design: true
  assets:
  - assets/catfoot.png
  - assets/examplemanda.jpg
  - assets/nyangsta.png
  - assets/femaleimage.jpg
  - assets/maleimage.jpg
